"""Pass 107: Gamla kyrkogården in Kalmar in detail, the Stagnell burial chapel and the medieval town
church (Bykyrkan, Storkyrkan) as a separate historical layer:
- the cemetery: grey fieldstone walls with a cast crown on the south-west, west and north sides (none on
  the south-east side), two black wrought-iron double gates, the gravel paths and the round gravel
  area of the grave plan, lawn, every grave of Åkerlund's grave plan placed from its drawn shape
  (standing stones, cast-iron crosses, lying slabs, chest tombs), the notable monuments modelled from
  their recorded sizes, the enclosures as low iron railings or stone kerbs, old trees, the Kristoffer
  pillar of red granite with its bronze figure, and a low limestone kerb marking the church
  foundations in the grass;
- the Stagnell burial chapel: octagonal, rendered ochre-yellow over a grey plinth, a recessed panel in
  each face, a plastered frieze under the eaves, the door in the north face with its half-columns and
  the red limestone tablet above, under a swept bell-shaped black sheet-iron roof with a point;
- Bykyrkan about 1610 (SM_Bykyrkan1610, historical_reconstruction=True): the five-aisled hall with its
  north and south chapel rows and their gables, the wide choir, the three-sided high choir, the west
  tower with two spires, the roof turret and pointed windows, after Olsson's reconstruction;
- it re-creates pass 98's SM_Slott98_Cemeteries and SM_Slott98_Trees without the generated graves,
  hedges and scatter trees inside Gamla kyrkogården; Södra kyrkogården and everything else in them
  is generated by pass 98's code unchanged.
Data: source/block107.json; see references/block107-notes.md.
"""
B107D=json.loads((R/'source/block107.json').read_text());block107_names=[];B107={}
for old in [k for k in list(materials) if k.startswith('M_Block107_')]:bpy.data.materials.remove(materials.pop(old))
for key,texture,target,rough,metal in [
 ('Lawn','TownStone',(.38,.50,.26),.95,0),('Gravel','TownStone',(.66,.62,.55),.95,0),('Mound','TownStone',(.34,.46,.23),.95,0),
 ('WallStone','TownStone',(.50,.49,.47),.92,0),('WallCap','TownStone',(.63,.62,.59),.90,0),('Iron','TownMetalGrey',(.06,.06,.065),.45,.40),
 ('Limestone','TownStone',(.62,.61,.58),.88,0),('RedLime','TownStone',(.56,.38,.31),.88,0),('Marble','TownIvory',(.90,.90,.88),.60,0),
 ('Kolmarden','TownIvory',(.80,.84,.79),.65,0),('BlackGranite','TownMetalGrey',(.09,.09,.10),.35,0),('RedGranite','TownStone',(.62,.42,.37),.70,0),
 ('GreyGranite','TownStone',(.55,.55,.56),.80,0),('Bronze','TownMetalGrey',(.30,.25,.16),.45,.60),('Clay','TownIvory',(.66,.48,.30),.80,0),
 ('Kerb','TownStone',(.64,.63,.59),.90,0),
 ('Ochre','TownIvory',(.86,.68,.38),.88,0),('Frieze','TownIvory',(.90,.76,.50),.88,0),('Plinth','TownStone',(.50,.50,.50),.90,0),
 ('RoofBlack','TownMetalGrey',(.07,.07,.075),.50,.30),('DoorBlack','TownMetalGrey',(.05,.05,.055),.45,.30),
 ('Bark','TownPaintBrown',(.25,.20,.16),.90,0),('Elm','TownStone',(.22,.34,.16),.95,0),('Lime','TownStone',(.28,.41,.18),.95,0),
 ('Chestnut','TownStone',(.19,.31,.14),.95,0),('Ash','TownStone',(.30,.42,.20),.95,0),
 ('Church','TownStone',(.80,.77,.70),.90,0),('ChurchDark','TownStone',(.70,.67,.61),.90,0),('ChurchRoof','TownMetalGrey',(.30,.28,.27),.70,.10),
 ('Spire','TownMetalGrey',(.24,.23,.23),.60,.20),('Window','TownMetalGrey',(.07,.08,.09),.30,.30),('ChurchDoor','TownPaintBrown',(.32,.22,.15),.70,0),
 ]:
 name='M_Block107_'+key;B107[key]=name;col=lin(target);tint=[round(c/m,4) for c,m in zip(col,lin(MEAN[texture]))]
 mat(name,col,rough,metal,texture);specs[name]['street16_tint']=tint;specs[name]['block107_target_srgb']=list(target)
 ma=materials[name];nodes=ma.node_tree.nodes;links=ma.node_tree.links;bsdf=nodes.get('Principled BSDF');src=bsdf.inputs['Base Color'].links[0].from_socket
 mix=nodes.new('ShaderNodeMixRGB');mix.blend_type='MULTIPLY';mix.inputs[0].default_value=1;mix.inputs[2].default_value=(*tint,1);links.new(src,mix.inputs[1]);links.new(mix.outputs[0],bsdf.inputs['Base Color'])
 for node in nodes:
  if node.bl_idname=='ShaderNodeTexImage' and node.image:
   twin=next((im for im in bpy.data.images if im!=node.image and im.filepath==node.image.filepath),None)
   if twin:loaded=node.image;node.image=twin;bpy.data.images.remove(loaded)
M107=B107;ZG107=0.30;ZL107=ZG107+.04
def b107_new(name,category):
 old=bpy.data.objects.get(name)
 if old:bpy.data.objects.remove(old,do_unlink=True)
 block107_names.append(name);return Mesh(name,category)
def drop_degenerate_faces107(obj,tol=1e-9):
 # Faces with no area, a repeated corner or a width under 0.1 mm have no UV frame for the export.
 import bmesh
 bm=bmesh.new();bm.from_mesh(obj.data)
 def _thin(f):
  L=max(e.calc_length() for e in f.edges);return L>0 and 2*f.calc_area()/L<1e-4
 bad=[f for f in bm.faces if f.calc_area()<tol or len({v.index for v in f.verts})<len(f.verts) or _thin(f)]
 if bad:bmesh.ops.delete(bm,geom=bad,context='FACES_ONLY')
 bm.to_mesh(obj.data);bm.free();obj.data.update();return len(bad)
def b107_finish(m,osm='',dp=107):
 obj=s21_finish(m);obj['block107_dropped_faces']=drop_degenerate_faces107(obj);print('BLOCK107_DROPPED',m.name,obj['block107_dropped_faces'],len(obj.data.polygons))
 obj['detail_pass']=dp;obj['reference_notes']='references/block107-notes.md';obj['osm_way']=osm;return obj
CEM107=[tuple(p) for p in B107D['cemetery']]
def in_cem107(x,y,margin=0.0):
 # inside the Gamla kyrkogården outline, or within margin of it
 c=False;n=len(CEM107)
 for i in range(n):
  (x1,y1),(x2,y2)=CEM107[i],CEM107[(i+1)%n]
  if (y1>y)!=(y2>y) and x<(x2-x1)*(y-y1)/(y2-y1)+x1:c=not c
 if c or margin<=0:return c
 for i in range(n):
  (x1,y1),(x2,y2)=CEM107[i],CEM107[(i+1)%n];dx,dy=x2-x1,y2-y1;t=max(0,min(1,((x-x1)*dx+(y-y1)*dy)/(dx*dx+dy*dy)))
  if math.dist((x,y),(x1+t*dx,y1+t*dy))<margin:return True
 return False

# ---------------------------------------------------------------- pass 98's two meshes, filtered
# Pass 98's generation code for SM_Slott98_Cemeteries and SM_Slott98_Trees, unchanged except that the
# generated graves, the boundary hedges and the trees of Gamla kyrkogården are left out (pass 107
# models that cemetery from its grave plan). Pass 98's tree seeds stay tied to the full tree list.
m=b107_new('SM_Slott98_Cemeteries','Slottsområdet/Cemeteries')
for c in B98D['cemeteries']:
 for p in c['pieces']:surf98(m,p,ZG107+.012,B98['Lawn'])
 if c['name']=='Gamla Kyrkogården':continue
 for e in c['edge']:
  for p,q in zip(e,e[1:]+e[:1]):
   L=math.dist(p,q)
   if L<.6:continue
   x,y,_,a=sf_edge(p,q);mx,my=(p[0]+q[0])/2,(p[1]+q[1])/2;inx,iny=-math.sin(a)*.6,math.cos(a)*.6
   m.box((mx+inx,my+iny,ZG107+.7),(L+.3,1.0,1.4),B98['Hedge'],a)
for x,y,ang,kind in B98D['graves']:
 if in_cem107(x,y):continue
 a=math.radians(ang)
 if kind==0:m.box((x,y,ZG107+.40),(.62,.14,.80),B98['Stone'],a)
 elif kind==1:m.box((x,y,ZG107+.50),(.50,.16,1.0),B98['StoneDark'],a)
 else:m.box((x,y,ZG107+.13),(.95,.55,.26),B98['Stone'],a)
obj=b107_finish(m,'24455361',98);obj['rebuilt_by_pass']=107
m=b107_new('SM_Slott98_Trees','Slottsområdet/Vegetation')
for i,(x,y,s) in enumerate(B98D['trees']):
 if in_cem107(x,y,1.0):continue
 rng=random.Random(98000+i);h=rng.uniform(9.5,13.5)*s;r=rng.uniform(3.4,4.8)*s;trunk=h*.40;z0=ZG107
 m.lathe(x,y,z0,[(.24,0),(.20,.4),(.16,trunk*.6),(.13,trunk)],B98['Bark'],8)
 cz=z0+trunk+(h-trunk)*.52
 blob79(m,(x,y,cz),(r*.85,r*.85,(h-trunk)*.46),B98['Leaf'],10,6)
 for k in range(3):
  a=rng.uniform(0,math.tau);d=rng.uniform(.35,.65)*r;rr=r*rng.uniform(.38,.55)
  blob79(m,(x+math.cos(a)*d,y+math.sin(a)*d,cz+rng.uniform(-.2,.35)*(h-trunk)*.5),(rr,rr,rr*.8),B98['LeafLight'] if k%2 else B98['Leaf'],8,5)
obj=b107_finish(m,'',98);obj['rebuilt_by_pass']=107

# SM_Slott98_Buildings_M held the chapel as a plain one-storey volume with windows (OSM way
# 500979084); pass 98's code re-creates that chunk without it, every other house unchanged.
WALLS107=['Ochre','White','PaleYellow','RedBoard','Grey','Brick','PaleGreen','White','Ochre','PaleYellow']  # pass 98's wall colours
m=b107_new('SM_Slott98_Buildings_M','Slottsområdet/Buildings')
for b in B98D['buildings']:
 cx_=sum(v[0] for v in b['outer'])/len(b['outer'])
 if not(-1150<=cx_<-850) or b['id']=='500979084':continue
 ring=[tuple(v) for v in b['outer']];h=int(hashlib.sha256(b['id'].encode()).hexdigest()[:6],16)
 levels=b['levels'];H=b['height'] or (levels*3.0+.5);H=max(2.6,min(H,28.0))
 wm=B98[WALLS107[h%len(WALLS107)]] if b['kind'] not in ('garage','shed','garages') else B98['Grey']
 for p,q in zip(ring,ring[1:]+ring[:1]):
  if math.dist(p,q)<.3:continue
  w={'p':list(p),'q':list(q),'z0':0.0}
  if levels<=0 or H<3.2 or b['kind'] in ('garage','garages','shed','roof'):bz_wall(m,w['p'],w['q'],0,H,[],wm)
  else:plain(m,w,H,wm,B98['Frame'],B98['Frame'],levels,ZG107+.9)
 r,Ls,Lt,fill=frame98(ring)
 if fill>.9 and min(Ls,Lt)<16 and len(ring)<=8:
  inset_roof(m,r,H,min(Ls,Lt)/2-.30,min(Ls,Lt)/2*.62,B98['Tile'] if h%3 else B98['DarkRoof'],.35)
 else:
  m.faces([(*v,H) for v in ring],[tuple(range(len(ring))),tuple(range(len(ring)-1,-1,-1))],B98['DarkRoof'])
  for p,q in zip(ring,ring[1:]+ring[:1]):
   L=math.dist(p,q)
   if L<.3:continue
   x,y,_,a=sf_edge(p,q);facade_box(m,x,y,0,.20,H+.3,L+.2,.25,.6,wm,a)
obj=b107_finish(m,'',98);obj['rebuilt_by_pass']=107

# ---------------------------------------------------------------- helpers
def surf107(m,piece,z,ma):
 rings=[piece['outer']]+piece.get('holes',[]);flatv=[(x,y) for r in rings for x,y in r]
 for t in tessellate_polygon([[Vector((x,y,0)) for x,y in r] for r in rings]):
  v=[(flatv[i][0],flatv[i][1],z) for i in t]
  if (v[1][0]-v[0][0])*(v[2][1]-v[0][1])-(v[1][1]-v[0][1])*(v[2][0]-v[0][0])<0:v.reverse()
  m.faces(v,[(0,1,2)],ma)
def R2(x,y,a,u,v):return (x+u*math.cos(a)-v*math.sin(a),y+u*math.sin(a)+v*math.cos(a))
def ring_prism107(m,pts,z0,z1,ma):
 # vertical prism over a convex ring given counter-clockwise or not
 a=sum(p[0]*q[1]-q[0]*p[1] for p,q in zip(pts,pts[1:]+pts[:1]))
 m.prism(pts if a>0 else pts[::-1],z0,z1,ma)
def plate107(m,o,t,n,poly,d0,d1,ma):
 # a flat plate on a wall plane: o origin, t along the wall, n outward normal, poly in (s,z), d0..d1 offsets
 k=len(poly);v=[(o[0]+t[0]*s+n[0]*d,o[1]+t[1]*s+n[1]*d,z) for d in (d0,d1) for s,z in poly]
 a=sum(p[0]*q[1]-q[0]*p[1] for p,q in zip(poly,poly[1:]+poly[:1]))
 f=[tuple(range(k,2*k)),tuple(range(k-1,-1,-1))] if a>0 else [tuple(range(2*k-1,k-1,-1)),tuple(range(k))]
 f+=[(i,(i+1)%k,(i+1)%k+k,i+k) for i in range(k)]
 m.faces(v,f,ma)
def pointed107(w,z0,z1,n=5):
 # outline of a pointed (two-centred) arch opening, width w, sill z0, apex z1
 r=w*.85;spring=z1-math.sqrt(r*r-(r-w/2)**2);pts=[(-w/2,z0),(w/2,z0)]
 c=(w/2-r)  # centre of the right-hand arc (on the left side)
 for i in range(n+1):
  t=i/n;ang=math.acos(min(1,(w/2-c)/r))*(1-t)+math.acos(min(1,(0-c)/r))*t;pts.append((c+r*math.cos(ang),spring+r*math.sin(ang)))
 left=[(-x,z) for x,z in pts[2:-1][::-1]]
 return pts[:2]+pts[2:-1]+[(0,z1)]+left
def pyramid107(m,base,z0,apex,ma):
 n=len(base);v=[(x,y,z0) for x,y in base]+[apex]
 a=sum(p[0]*q[1]-q[0]*p[1] for p,q in zip(base,base[1:]+base[:1]))
 f=[(i,(i+1)%n,n) if a>0 else ((i+1)%n,i,n) for i in range(n)]+[tuple(range(n-1,-1,-1)) if a>0 else tuple(range(n))]
 m.faces(v,f,ma)
def cross107(m,x,y,z,a,h,w,ma,t=.07,trefoil=False):
 # a cast-iron cross: post, arms at 70 %, optional trefoil lobes at the ends
 m.box((x,y,z+h/2),(t,t*1.3,h),ma,a);ay=z+h*.70;m.box((x,y,ay),(w,t*1.3,t),ma,a)
 if trefoil:
  for u,zz in [(-w/2,ay),(w/2,ay),(0,z+h)]:
   px,py=R2(x,y,a,u,0);m.box((px,py,zz),(t*2.2,t*1.4,t*2.2),ma,a)
def rail107(m,x,y,a,L,W,h,ma,z0,step=.16):
 # a low iron railing round a rectangle: posts, top and bottom rails, bars
 for su,sv in [(-1,-1),(1,-1),(1,1),(-1,1)]:
  px,py=R2(x,y,a,su*L/2,sv*W/2);m.box((px,py,z0+h/2+.04),(.06,.06,h+.08),ma,a)
 for (u0,v0),(u1,v1) in [((-L/2,-W/2),(L/2,-W/2)),((L/2,-W/2),(L/2,W/2)),((L/2,W/2),(-L/2,W/2)),((-L/2,W/2),(-L/2,-W/2))]:
  ln=math.dist((u0,v0),(u1,v1));aa=a+math.atan2(v1-v0,u1-u0);cx,cy=R2(x,y,a,(u0+u1)/2,(v0+v1)/2)
  for zz in (z0+.08,z0+h-.03):m.box((cx,cy,zz),(ln,.03,.03),ma,aa)
  nb=int(ln/step)
  for k in range(1,nb):
   t=k/nb;px,py=R2(x,y,a,u0+(u1-u0)*t,v0+(v1-v0)*t);m.box((px,py,z0+h/2),(.018,.018,h-.06),ma,aa)

# ---------------------------------------------------------------- the cemetery
m=b107_new('SM_GamlaKyrkogarden107','Slottsområdet/Gamla kyrkogården')
for p in B107D['lawn']:surf107(m,p,ZL107,M107['Lawn'])
for p in B107D['gravel']:surf107(m,p,ZL107+.012,M107['Gravel'])
# Walls: 0.75 m thick, 1.0-1.3 m high (RAÄ), grey fieldstone with a cast crown; the centre line
# runs 0.375 m inside the OSM outline.
def inward107(p,q):
 x,y,L,a=sf_edge(p,q);nx,ny=-math.sin(a),math.cos(a)
 return (nx,ny) if in_cem107(x+nx*.5,y+ny*.5) else (-nx,-ny)
for run in B107D['walls']:
 for j,(p,q) in enumerate(zip(run,run[1:])):
  L=math.dist(p,q)
  if L<.05:continue
  nx,ny=inward107(p,q);x,y,_,a=sf_edge(p,q);x+=nx*.375;y+=ny*.375
  hh=1.0+.3*(int(hashlib.sha256(f'{p}'.encode()).hexdigest()[:6],16)%100)/100
  s0=-L/2-(.375 if j>0 else 0);s1=L/2+(.375 if j<len(run)-2 else 0)
  cx,cy=R2(x,y,a,(s0+s1)/2,0)
  m.box((cx,cy,ZG107+hh/2-.05),(s1-s0,.75,hh+.1),M107['WallStone'],a)
  m.box((cx,cy,ZG107+hh+.06),(s1-s0+.02,.82,.12),M107['WallCap'],a)
# Gates: two black wrought-iron double gates between stone piers.
for gt in B107D['gates']:
 x,y,a,w=gt['x'],gt['y'],gt['a'],gt['w'];nx,ny=-math.sin(a),math.cos(a)
 if not in_cem107(x+nx*.5,y+ny*.5):nx,ny=-nx,-ny
 x+=nx*.375;y+=ny*.375
 for s in (-1,1):
  px,py=R2(x,y,a,s*(w/2+.35),0);m.box((px,py,ZG107+.8),(.7,.8,1.6),M107['WallStone'],a);m.box((px,py,ZG107+1.66),(.8,.9,.12),M107['WallCap'],a)
  m.box((*R2(x,y,a,s*(w/2+.35),0),ZG107+1.80),(.22,.22,.16),M107['WallCap'],a)
 for s in (-1,1):
  lw=w/2-.04;u0=s*.02;u1=s*(w/2-.02)
  for zz in (ZG107+.15,ZG107+.85,ZG107+1.45):m.box((*R2(x,y,a,(u0+u1)/2,0),zz),(lw,.04,.05),M107['Iron'],a)
  nb=12
  for k in range(nb+1):
   u=u0+(u1-u0)*k/nb;hb=1.45+.18*math.sin(math.pi*k/nb)
   m.box((*R2(x,y,a,u,0),ZG107+.1+hb/2),(.02 if 0<k<nb else .05,.025 if 0<k<nb else .05,hb),M107['Iron'],a)
# Graves from the grave plan.
def stone_mat107(seed,red_share=4):
 return [M107['Limestone'],M107['RedLime'],M107['Limestone'],M107['GreyGranite'],M107['RedLime'],M107['Marble'],M107['Limestone']][seed%7]
for g in B107D['graves']:
 x,y,a,L,W,h,k,sd=g['x'],g['y'],g['a'],g['L'],g['W'],g['h'],g['kind'],g['seed'];z=ZL107
 if k=='stone':
  ma=stone_mat107(sd);m.box((x,y,z+.05),(L+.15,.42,.10),ma,a);m.box((x,y,z+.1+h/2),(L,.17,h),ma,a)
  if sd%5==0:m.box((x,y,z+.1+h+.04),(L*.6,.17,.08),ma,a)
 elif k=='cross':
  m.box((x,y,z+.08),(.45,.32,.16),M107['Limestone'],a);cross107(m,x,y,z+.16,a,h-.1,min(.55,L*.7),M107['Iron'],.06,sd%2==0)
 elif k=='ironcross':
  m.box((x,y,z+.1),(.6,.4,.2),M107['Limestone'],a);cross107(m,x,y,z+.2,a,h-.2,g.get('cw',.7),M107['Iron'],.08,True)
 elif k=='ironcross_ped':
  # Bishop Magnus Stagnelius, no. 28: cast-iron cross 1.87 x 1.07 m on a stone pedestal, on the plot
  m.box((x,y,z+.04),(L,W,.08),M107['Limestone'],a);m.box((x,y,z+.33),(.75,.55,.5),M107['Limestone'],a);m.box((x,y,z+.62),(.85,.65,.08),M107['Limestone'],a)
  cross107(m,x,y,z+.66,a,1.87,1.07,M107['Iron'],.10,True)
 elif k in('slab','block'):
  m.box((x,y,z+h/2),(L,W,h),M107[g['mat']] if 'mat' in g else stone_mat107(sd),a)
 elif k=='tumba':
  ma=M107[g['mat']] if 'mat' in g else stone_mat107(sd);m.box((x,y,z+(h-.1)/2),(L,W,h-.1),ma,a);m.box((x,y,z+h-.05),(L+.12,W+.12,.1),ma,a)
 elif k=='tumba_rail':
  # Swarss, no. 50: a low tomb 2.23 x 1.62 x 0.55 m in an iron railing 1.33 m high
  m.box((x,y,z+.225),(L,W,.45),M107['Limestone'],a);m.box((x,y,z+.5),(L+.12,W+.12,.1),M107['Limestone'],a)
  rail107(m,x,y,a,L+1.0,W+1.0,1.33,M107['Iron'],z)
 elif k=='round':
  m.cylinder(x,y,z,min(.32,max(.18,L/2*.6)),h,stone_mat107(sd),12)
 elif k=='urn':
  # Balabrega, no. 96: a Höganäs urn 1.06 m high, 0.52 m across, on a 0.57 m limestone slab
  m.box((x,y,z+.05),(.57,.57,.1),M107['Limestone'],a)
  m.lathe(x,y,z+.1,[(.12,0),(.10,.08),(.08,.14),(.18,.24),(.26,.45),(.25,.62),(.16,.80),(.13,.86),(.17,.92),(.15,.98),(.04,1.06)],M107['Clay'],12)
 elif k=='pillar':
  # Kinnecke, no. 74: a four-sided red limestone pillar on a postament with a mushroom-like crown
  m.box((x,y,z+.2),(.7,.7,.4),M107['RedLime'],a);m.box((x,y,z+.4+.9),(.42,.42,1.8),M107['RedLime'],a)
  m.lathe(x,y,z+2.2,[(.22,0),(.34,.12),(.30,.22),(.06,.30)],M107['RedLime'],12)
 elif k=='obelisk':
  # Korsseman, no. 139: red limestone obelisk 1.35 m on a stepped base, 2.4 m in all
  for i,(s,hh) in enumerate([(1.0,.2),(.8,.2),(.6,.65)]):m.box((x,y,z+sum(v for _,v in [(1.0,.2),(.8,.2),(.6,.65)][:i])+hh/2),(s,s,hh),M107['RedLime'],a)
  zb=z+1.05;b=[R2(x,y,a,u,v) for u,v in [(-.22,-.22),(.22,-.22),(.22,.22),(-.22,.22)]];t=[R2(x,y,a,u,v) for u,v in [(-.14,-.14),(.14,-.14),(.14,.14),(-.14,.14)]]
  m.faces([(*p,zb) for p in b]+[(*p,zb+1.15) for p in t],[(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7),(3,2,1,0)],M107['RedLime']);pyramid107(m,t,zb+1.15,(x,y,zb+1.35),M107['RedLime'])
 elif k=='obelisk_mound':
  # Per Wijk, no. 15: polished black granite obelisk about 3.5 m high on a round mound 3 m across
  m.lathe(x,y,z-.02,[(1.5,0),(1.35,.18),(1.0,.36),(.5,.46),(.05,.5)],M107['Mound'],16)
  m.box((x,y,z+.55+.2),(.9,.9,.4),M107['BlackGranite'],a);m.box((x,y,z+.95+.15),(.7,.7,.3),M107['BlackGranite'],a)
  zb=z+1.25;b=[R2(x,y,a,u,v) for u,v in [(-.28,-.28),(.28,-.28),(.28,.28),(-.28,.28)]];t=[R2(x,y,a,u,v) for u,v in [(-.15,-.15),(.15,-.15),(.15,.15),(-.15,.15)]]
  m.faces([(*p,zb) for p in b]+[(*p,zb+2.05) for p in t],[(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7),(3,2,1,0)],M107['BlackGranite']);pyramid107(m,t,zb+2.05,(x,y,zb+2.25),M107['BlackGranite'])
 elif k=='marblecross':
  m.box((x,y,z+.12),(.6,.45,.24),M107['Kolmarden'],a);cross107(m,x,y,z+.24,a,1.03,.55,M107['Kolmarden'],.12)
 elif k=='marblestone':
  m.box((x,y,z+.1),(.8,.45,.2),M107['Kolmarden'],a);m.box((x,y,z+.2+.62),(.62,.2,1.24),M107['Kolmarden'],a)
# Enclosures: iron railings (36 Wiberg 3.2 x 3.2 m, 44 on limestone blocks 5.3 x 3.9 x 0.92 m, 18, 153)
# and stone kerbs (34, 35).
for e in B107D['enclosures']:
 x,y,a,L,W,h=e['x'],e['y'],e['a'],e['L'],e['W'],e['h']
 if e['kind']=='kerb':
  for (u0,v0),(u1,v1) in [((-L/2,-W/2),(L/2,-W/2)),((L/2,-W/2),(L/2,W/2)),((L/2,W/2),(-L/2,W/2)),((-L/2,W/2),(-L/2,-W/2))]:
   cx,cy=R2(x,y,a,(u0+u1)/2,(v0+v1)/2);m.box((cx,cy,ZL107+h/2-.03),(math.dist((u0,v0),(u1,v1))+.25,.25,h+.06),M107['Limestone'],a+math.atan2(v1-v0,u1-u0))
 else:
  m.box((x,y,ZL107+.04),(L+.2,W+.2,.08),M107['Limestone'],a) if e['kind']=='rail' else None
  if e['kind']=='rail_blocks':
   for su,sv in [(-1,-1),(1,-1),(1,1),(-1,1)]:m.box((*R2(x,y,a,su*L/2,sv*W/2),ZL107+.15),(.35,.35,.3),M107['Limestone'],a)
  rail107(m,x,y,a,L,W,h,M107['Iron'],ZL107+(.3 if e['kind']=='rail_blocks' else .08))
# Johansson's monument no. 20: white marble, about 2.25 m, an urn on a pedestal.
x,y=B107D['urn20'];m.box((x,y,ZL107+.12),(.8,.8,.24),M107['Marble']);m.box((x,y,ZL107+.24+.6),(.55,.55,1.2),M107['Marble']);m.box((x,y,ZL107+1.48),(.66,.66,.08),M107['Marble'])
m.lathe(x,y,ZL107+1.52,[(.12,0),(.08,.08),(.2,.2),(.24,.38),(.16,.56),(.1,.6),(.12,.66),(.03,.73)],M107['Marble'],12)
x,y=B107D['ring154'];m.cylinder(x,y,ZL107,.18,.5,M107['Limestone'],10)
# The Kristoffer pillar: light red granite, 2.1 x 0.61 x 0.52 m, on a granite plate 0.91 x 0.91 x 0.1 m,
# on the nave centre line, the bronze statuette of St Christopher with the child on his shoulder on top.
x,y=B107D['kristoffer']['xy'];a=B107D['kristoffer']['axis']
m.box((x,y,ZL107+.05),(.91,.91,.10),M107['RedGranite'],a);m.box((x,y,ZL107+.1+1.05),(.61,.52,2.1),M107['RedGranite'],a)
zt=ZL107+2.2;m.box((x,y,zt+.03),(.42,.36,.06),M107['Bronze'],a)
# the statuette, about 0.85 m: legs and body, head, the child on the right shoulder, the staff
m.lathe(x,y,zt+.06,[(.12,0),(.11,.25),(.13,.45),(.12,.58),(.07,.64)],M107['Bronze'],8);blob79(m,(x,y,zt+.71),(.07,.07,.08),M107['Bronze'],8,5)
bx,by=R2(x,y,a,-.06,.08);blob79(m,(bx,by,zt+.74),(.06,.05,.07),M107['Bronze'],6,4);blob79(m,(bx,by,zt+.84),(.04,.04,.045),M107['Bronze'],6,4)
sx,sy=R2(x,y,a,.17,.02);m.box((sx,sy,zt+.45),(.03,.03,.9),M107['Bronze'],a)
# Bykyrkan's outline today: a low limestone kerb (0.12 m high, 0.3 m wide) of slabs set in the grass.
for run in B107D['kerb']:
 for p,q in zip(run,run[1:]):
  L=math.dist(p,q);n=max(1,round(L/1.2));x0,y0,_,a=sf_edge(p,q)
  for j in range(n):
   s=-L/2+(j+.5)*L/n;cx,cy=R2(x0,y0,a,s,0);m.box((cx,cy,ZL107+.04),(L/n-.03,.30,.16),M107['Kerb'],a)
obj=b107_finish(m,'149032114')

# ---------------------------------------------------------------- old trees
m=b107_new('SM_GamlaKyrkogarden107_Trees','Slottsområdet/Vegetation')
TREE107={'elm':(19,7.0,'Elm',.42),'lime':(17,5.5,'Lime',.40),'chestnut':(15,6.5,'Chestnut',.32),'weeping_ash':(10,4.5,'Ash',.30)}
for i,t in enumerate(B107D['trees']):
 x,y,s=t['x'],t['y'],t['s'];hh,r,lm,tf=TREE107[t['sp']];hh*=s;r*=s;rng=random.Random(107000+i);trunk=hh*tf;z0=ZG107
 m.lathe(x,y,z0,[(.45*s,0),(.36*s,.6),(.30*s,trunk*.6),(.24*s,trunk)],M107['Bark'],10)
 if t['sp']=='weeping_ash':
  cz=z0+hh*.62;blob79(m,(x,y,cz),(r*.8,r*.8,hh*.28),M107[lm],10,6)
  for k in range(7):
   a=k*math.tau/7+rng.uniform(-.2,.2);blob79(m,(x+math.cos(a)*r*.75,y+math.sin(a)*r*.75,cz-hh*.22),(r*.38,r*.38,hh*.30),M107[lm],8,5)
  continue
 if t['sp']=='elm':cz=z0+trunk+(hh-trunk)*.58;crown107=(r,r,(hh-trunk)*.42)
 elif t['sp']=='lime':cz=z0+trunk+(hh-trunk)*.50;crown107=(r*.85,r*.85,(hh-trunk)*.52)
 else:cz=z0+trunk+(hh-trunk)*.48;crown107=(r,r,(hh-trunk)*.50)
 blob79(m,(x,y,cz),crown107,M107[lm],12,7)
 for k in range(5):
  a=rng.uniform(0,math.tau);d=rng.uniform(.4,.7)*r;rr=r*rng.uniform(.40,.55)
  blob79(m,(x+math.cos(a)*d,y+math.sin(a)*d,cz+rng.uniform(-.35,.35)*crown107[2]),(rr,rr,rr*.85),M107[lm],8,5)
obj=b107_finish(m,'149032114')

# ---------------------------------------------------------------- the Stagnell burial chapel
m=b107_new('SM_Stagnellska107','Slottsområdet/Gamla kyrkogården')
CH107=B107D['chapel'];cx,cy=CH107['c'];ap=CH107['r']*math.cos(math.pi/8);z0=ZL107+.012
# A face toward true north (the door): face normals at the local angle of true north + k*45 degrees.
nor=math.radians(90-CH107['north_bearing'])
def oct107(apo):return [(cx+apo/math.cos(math.pi/8)*math.cos(nor+math.pi/8+k*math.pi/4),cy+apo/math.cos(math.pi/8)*math.sin(nor+math.pi/8+k*math.pi/4)) for k in range(8)]
ring_prism107(m,oct107(ap+.06),z0-.1,z0+.45,M107['Plinth'])
ZW=z0+3.25;ring_prism107(m,oct107(ap-.15),z0+.45,ZW,M107['Ochre'])
fw=2*ap*math.tan(math.pi/8);PW=.30
for k in range(8):
 ph=nor+k*math.pi/4;n=(math.cos(ph),math.sin(ph));t=(-n[1],n[0]);a=math.atan2(t[1],t[0])
 o=(cx+n[0]*(ap-.075),cy+n[1]*(ap-.075))
 for s in (-1,1):m.box((o[0]+t[0]*s*(fw/2-PW/2),o[1]+t[1]*s*(fw/2-PW/2),(z0+.45+ZW)/2),(PW,.15,ZW-z0-.45),M107['Ochre'],a)
 m.box((o[0],o[1],z0+.45+.09),(fw,.15,.18),M107['Ochre'],a)
 of=(cx+n[0]*(ap-.055),cy+n[1]*(ap-.055));m.box((of[0],of[1],ZW-.22),(fw+.02,.19,.44),M107['Frieze'],a)
 if k==0:
  # the north face: black sheet-iron door, a half-column each side, the red limestone tablet above
  od=(cx+n[0]*(ap-.15),cy+n[1]*(ap-.15));m.box((od[0]+n[0]*.03,od[1]+n[1]*.03,z0+.45+.95),(.95,.06,1.9),M107['DoorBlack'],a)
  for s in (-1,1):
   px,py=od[0]+t[0]*s*.66+n[0]*.02,od[1]+t[1]*s*.66+n[1]*.02
   m.cylinder(px,py,z0+.45,.12,.12,M107['Ochre'],10);m.cylinder(px,py,z0+.57,.09,1.75,M107['Ochre'],10);m.cylinder(px,py,z0+2.32,.12,.10,M107['Ochre'],10)
  m.box((od[0]+n[0]*.04,od[1]+n[1]*.04,z0+2.42+.2),(1.0,.08,.4),M107['RedLime'],a)
ring_prism107(m,oct107(ap+.22),ZW,ZW+.12,M107['Frieze'])
# Bell-shaped swept roof of black sheet iron, about 3 m with its point.
prof=[(ap+.34,0),(ap+.30,.08),(ap*.92,.35),(ap*.72,.75),(ap*.52,1.25),(ap*.34,1.75),(ap*.19,2.20),(ap*.08,2.55)]
vs=[];zr=ZW+.12
for apo,dz in prof:vs+= [(x,y,zr+dz) for x,y in oct107(apo)]
f=[tuple(range(7,-1,-1))]
for j in range(len(prof)-1):f+=[(j*8+i,j*8+(i+1)%8,(j+1)*8+(i+1)%8,(j+1)*8+i) for i in range(8)]
top=len(vs);vs.append((cx,cy,zr+2.95));f+=[((len(prof)-1)*8+i,(len(prof)-1)*8+(i+1)%8,top) for i in range(8)]
m.faces(vs,f,M107['RoofBlack'])
m.lathe(cx,cy,zr+2.80,[(.05,0),(.07,.06),(.02,.30)],M107['RoofBlack'],8)
obj=b107_finish(m,'500979084')

# ---------------------------------------------------------------- Bykyrkan about 1610 (historical layer)
m=b107_new('SM_Bykyrkan1610','Historik/Bykyrkan 1610')
CHD=B107D['church'];CO=CHD['origin'];CU_=CHD['u'];CV_=CHD['v'];SP=CHD['spec'];ZC=ZG107
def X107(u,v,z=None):
 p=(CO[0]+CU_[0]*u+CV_[0]*v,CO[1]+CU_[1]*u+CV_[1]*v);return p if z is None else (*p,z)
AU=math.atan2(CU_[1],CU_[0])
def blk107(u,v,z0,z1,ma):ring_prism107(m,[X107(u[0],v[0]),X107(u[1],v[0]),X107(u[1],v[1]),X107(u[0],v[1])],z0,z1,ma)
def saddle107(u,v,eave,ridge,along,ma,gm,ov=.35,gables=(True,True)):
 # a saddle roof over the rectangle u x v, ridge along u ('u') or v ('v'), with gable triangles
 if along=='u':
  vm=(v[0]+v[1])/2;hv=(v[1]-v[0])/2;dz=(ridge-eave)/hv*ov
  P=lambda uu,vv,zz:X107(uu,vv,ZC+zz)
  a0,a1=u[0]-ov*.5,u[1]+ov*.5
  m.faces([P(a0,v[0]-ov,eave-dz),P(a1,v[0]-ov,eave-dz),P(a1,vm,ridge),P(a0,vm,ridge)],[(0,1,2,3)],ma)
  m.faces([P(a1,v[1]+ov,eave-dz),P(a0,v[1]+ov,eave-dz),P(a0,vm,ridge),P(a1,vm,ridge)],[(0,1,2,3)],ma)
  m.faces([P(a0,v[0]-ov,eave-dz-.15),P(a1,v[0]-ov,eave-dz-.15),P(a1,v[0]-ov,eave-dz),P(a0,v[0]-ov,eave-dz)],[(0,1,2,3)],ma)
  m.faces([P(a1,v[1]+ov,eave-dz-.15),P(a0,v[1]+ov,eave-dz-.15),P(a0,v[1]+ov,eave-dz),P(a1,v[1]+ov,eave-dz)],[(0,1,2,3)],ma)
  for g,uu,sgn in [(gables[0],u[0],-1),(gables[1],u[1],1)]:
   if g:plate107(m,X107(uu,vm),CV_,(CU_[0]*sgn,CU_[1]*sgn),[(-hv,ZC+eave),(hv,ZC+eave),(0,ZC+ridge-.05)],-.05,.0,gm)
 else:
  um=(u[0]+u[1])/2;hu=(u[1]-u[0])/2;dz=(ridge-eave)/hu*ov
  P=lambda uu,vv,zz:X107(uu,vv,ZC+zz)
  b0,b1=v[0]-ov*.5,v[1]+ov*.5
  m.faces([P(u[1]+ov,b0,eave-dz),P(u[1]+ov,b1,eave-dz),P(um,b1,ridge),P(um,b0,ridge)],[(0,1,2,3)],ma)
  m.faces([P(u[0]-ov,b1,eave-dz),P(u[0]-ov,b0,eave-dz),P(um,b0,ridge),P(um,b1,ridge)],[(0,1,2,3)],ma)
  for g,vv,sgn in [(gables[0],v[0],-1),(gables[1],v[1],1)]:
   if g:plate107(m,X107(um,vv),CU_,(CV_[0]*sgn,CV_[1]*sgn),[(-hu,ZC+eave),(hu,ZC+eave),(0,ZC+ridge-.05)],-.05,.0,gm)
def window107(u,v,side,w,z0,z1,face_n,ma=None):
 # a pointed window as a dark glazed plate just proud of the wall face at (u,v)
 o=X107(u,v);n=(CU_[0]*face_n[0]+CV_[0]*face_n[1],CU_[1]*face_n[0]+CV_[1]*face_n[1]);t=(-n[1],n[0])
 plate107(m,o,t,n,[(s,ZC+z) for s,z in pointed107(w,z0,z1)],.0,.04,ma or M107['Window'])
W_,R_,D_=M107['Church'],M107['ChurchRoof'],M107['ChurchDark']
# Chapel rows: Kalkkoret and Södra valvet with their gables to the west; the chapels with a gable each
# to the north and the south (the saw-tooth row of the south elevation).
for c in [SP['kalkkoret'],SP['sodra_valvet']]:
 blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_);saddle107(c['u'],c['v'],c['eave'],c['ridge'],'u',R_,W_,gables=(True,False))
for c in SP['north']:blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_);saddle107(c['u'],c['v'],c['eave'],c['ridge'],'v',R_,W_,gables=(False,True))
for c in SP['south']:blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_);saddle107(c['u'],c['v'],c['eave'],c['ridge'],'v',R_,W_,gables=(True,False))
c=SP['sakristia'];blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_);saddle107(c['u'],c['v'],c['eave'],c['ridge'],'u',R_,W_,gables=(False,True))
c=SP['west_low'];blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_)
# The hall church and the wide choir under one high roof, eaves 13.5 m, ridge 22 m.
c=SP['hall'];blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_);saddle107(c['u'],c['v'],c['eave'],c['ridge'],'u',R_,W_,gables=(True,False))
c=SP['choir'];blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_);saddle107(c['u'],c['v'],c['eave'],c['ridge'],'u',R_,W_,gables=(False,True))
# The high choir: three-sided east end, eaves 8 m, ridge 14.5 m.
hk=SP['hogkor'];HK=[tuple(p) for p in CHD['hogkor_uv']];hw=hk['v'][1]
ring_prism107(m,[X107(*p) for p in HK],ZC-.2,ZC+hk['eave'],W_)
P107=lambda uu,vv,zz:X107(uu,vv,ZC+zz);ov=.35
m.faces([P107(hk['u'][0],-hw-ov,hk['eave']-.3),P107(hk['apse'],-hw-ov,hk['eave']-.3),P107(hk['apse'],0,hk['ridge']),P107(hk['u'][0],0,hk['ridge'])],[(0,1,2,3)],R_)
m.faces([P107(hk['apse'],hw+ov,hk['eave']-.3),P107(hk['u'][0],hw+ov,hk['eave']-.3),P107(hk['u'][0],0,hk['ridge']),P107(hk['apse'],0,hk['ridge'])],[(0,1,2,3)],R_)
ex=[(hk['apse'],-hw-ov),(hk['u'][1]+ov,-hw*.42-ov*.4),(hk['u'][1]+ov,hw*.42+ov*.4),(hk['apse'],hw+ov)]
for p,q in zip(ex,ex[1:]):m.faces([P107(*p,hk['eave']-.3),P107(*q,hk['eave']-.3),P107(hk['apse'],0,hk['ridge'])],[(0,1,2)],R_)
# The west tower, 9 x 14 m, walls to 26 m, with two spires side by side to about 52 m.
c=SP['tower'];blk107(c['u'],c['v'],ZC-.2,ZC+c['eave'],W_)
um=(c['u'][0]+c['u'][1])/2
for v0,v1 in [(c['v'][0],0.0),(0.0,c['v'][1])]:
 vm=(v0+v1)/2;sk=[(c['u'][0]-.6,v0-.6),(c['u'][1]+.6,v0-.6),(c['u'][1]+.6,v1+.6),(c['u'][0]-.6,v1+.6)];bs=[(c['u'][0]+.1,v0+.1),(c['u'][1]-.1,v0+.1),(c['u'][1]-.1,v1-.1),(c['u'][0]+.1,v1-.1)]
 vs=[P107(*p,c['eave']-.1) for p in sk]+[P107(*p,c['eave']+1.6) for p in bs]
 m.faces(vs,[(3,2,1,0),(0,1,5,4),(1,2,6,5),(2,3,7,6),(3,0,4,7)],M107['Spire'])
 pyramid107(m,[X107(*p) for p in bs],ZC+c['eave']+1.6,P107(um,vm,c['spire_top']),M107['Spire'])
 m.lathe(*X107(um,vm),ZC+c['spire_top']-.3,[(.08,0),(.05,.8),(.02,1.0)],M107['Spire'],6)
for face,(uu,vv,fn) in {'w':(c['u'][0],0,(-1,0)),'s':(um,c['v'][0],(0,-1)),'n':(um,c['v'][1],(0,1)),'e':(c['u'][1],0,(1,0))}.items():
 off=(0,0)
 for dv in ((-3.5,3.5) if face in 'we' else (0,)):
  uw,vw=(uu,vv+dv) if face in 'we' else (uu+dv,vv)
  window107(uw,vw,face,1.2,19.5,22.0,fn)
  if face in 'ws':window107(uw,vw,face,.5,14.5,16.0,fn)
# Roof turret over the choir, about 30 m.
c=SP['turret'];tu=c['u'];bs=[(tu-.7,-.2),(tu+.7,-.2),(tu+.7,1.2),(tu-.7,1.2)]
ring_prism107(m,[X107(*p) for p in bs],ZC+c['ridge']-1.5,ZC+c['ridge']+3.0,R_)
pyramid107(m,[X107(*p) for p in [(tu-.9,-.4),(tu+.9,-.4),(tu+.9,1.4),(tu-.9,1.4)]],ZC+c['ridge']+3.0,P107(tu,.5,c['top']),M107['Spire'])
# Windows: one pointed window in each chapel bay, two in Södra valvet and Kalkkoret, tall ones in the
# choir and the high choir; small windows in the south gables; the main door (Stora kyrkodörren) and
# the round window above it in the porch (Vapenhuset, bay E) facing the burial chapel.
for c in SP['south']:
 um_=(c['u'][0]+c['u'][1])/2
 if c['name']=='E':
  du=SP['porch_door_u'];window107(du,c['v'][0],'s',2.0,0,3.8,(0,-1),M107['ChurchDoor'])
  o=X107(du,c['v'][0]);n=(-CV_[0],-CV_[1]);t=(-n[1],n[0]);plate107(m,o,t,n,[(.5*math.cos(i*math.pi/6),ZC+5.0+.5*math.sin(i*math.pi/6)) for i in range(12)],0,.04,M107['Window'])
 else:window107(um_,c['v'][0],'s',1.5,1.2,5.4,(0,-1))
 window107(um_,c['v'][0],'s',.7,7.6,8.9,(0,-1))
for c in SP['north']:
 um_=(c['u'][0]+c['u'][1])/2;window107(um_,c['v'][1],'n',1.5,1.2,5.4,(0,1));window107(um_,c['v'][1],'n',.7,7.6,8.9,(0,1))
for uu in (3.0,8.0):window107(uu,SP['sodra_valvet']['v'][0],'s',1.3,1.2,4.6,(0,-1))
window107(SP['sodra_valvet']['u'][0],-12.75,'w',1.2,.0,2.8,(-1,0),M107['ChurchDoor']);window107(SP['kalkkoret']['u'][0],14.85,'w',1.2,.0,2.8,(-1,0),M107['ChurchDoor'])
for uu in (6.5,10.5):window107(uu,SP['kalkkoret']['v'][1],'n',1.3,1.2,4.6,(0,1))
ch=SP['choir']
for uu in (56.5,62.5):
 window107(uu,ch['v'][1],'n',1.8,4.0,11.5,(0,1))
 window107(uu,ch['v'][0],'s',1.8,7.2,11.5,(0,-1))
window107(69.0,-hw,'s',1.4,1.5,6.5,(0,-1));window107(69.0,hw,'n',1.4,1.5,6.5,(0,1));window107(hk['u'][1],0,'e',1.4,1.5,6.5,(1,0))
for sgn in (-1,1):
 # the two oblique faces of the three-sided end
 pa=(hk['apse'],sgn*hw);pb=(hk['u'][1],sgn*hw*.42);mu,mv=(pa[0]+pb[0])/2,(pa[1]+pb[1])/2
 du,dv=pb[0]-pa[0],pb[1]-pa[1];Ln=math.hypot(du,dv);fn=(abs(dv)/Ln,sgn*abs(du)/Ln)
 window107(mu,mv,'x',1.3,1.5,6.3,fn)
obj=b107_finish(m,'');obj['historical_reconstruction']=True;obj['reconstruction_date']='about 1610'
obj['reconstruction_source']='M. Olsson, Sveriges kyrkor vol. 158 (1974), pl. II, V, VII; placed on S. Rosman 1924, pl. I'

def sv_camera(name,x,y,h,heading,pitch,vfov=90,match='height'):
 b=math.radians(heading+28.2);t=(x+30*math.sin(b),y+30*math.cos(b),h+30*math.tan(math.radians(pitch)))
 lens=(9.667 if match=='width' else 11.25)/math.tan(math.radians(vfov/2))
 return (name,(round(x,2),round(y,2),round(h,2)),tuple(round(v,2) for v in t),round(lens,2))
block107_cameras=[sv_camera('526_Block107_Cal_SouthGate',-953.0,-6.0,2.0,8,0,70),sv_camera('527_Block107_Cal_Chapel',-941.2,16.8,2.0,225,5,60),
 sv_camera('528_Block107_Cal_Kristoffer',-929.3,23.9,1.8,218,8,60),sv_camera('529_Block107_Cal_NorthLawn',-900.0,70.0,2.0,102,-2,70),
 ('530_Block107_Aerial',(-860.0,-40.0,90.0),(-905.0,40.0,2.0),24),('531_Block107_Aerial_Bykyrkan1610',(-880.0,-60.0,60.0),(-930.0,25.0,8.0),24)]
print('BLOCK107_GEOMETRY',len(block107_names))
import os as _os107
if _os107.environ.get('BLOCK107_HIDE_HISTORY'):
 # sandbox only: render today's cemetery without the historical layer
 bpy.data.objects['SM_Bykyrkan1610'].hide_render=True
