from pathlib import Path
R=Path(__file__).resolve().parents[1]
base=(R/'scripts/rebuild_larmtorget.py').read_text();marker="exec(compile((R/'scripts/build_larmtorget_facades.py').read_text()";exec(compile(base[:base.index(marker)],str(R/'scripts/rebuild_larmtorget.py'),'exec'))
head=(R/'scripts/build_pass18.py').read_text();head=head[:head.index("for filename in ['build_pass18_landmarks.py'")];exec(compile(head,'pass18_helpers','exec'))
tree=ast.parse((R/'scripts/build_pass18_extra.py').read_text());tree.body=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='outside_box'];exec(compile(tree,'clip','exec'))
code=(R/'scripts/build_street22.py').read_text();exec(compile(code[:code.index('# Pale three-storey Kaggensgatan/Fiskaregatan corner')],'street22_joinery','exec'))
# Pass 89 reuses the pass 26 and 28-88 helpers, which rebuild those houses unchanged, then adds
# the houses on the south side of east Storgatan. Only the pass 89 meshes are exported.
exec(compile((R/'scripts/build_larm26.py').read_text(),'build_larm26.py','exec'))
exec(compile((R/'scripts/build_block28.py').read_text(),'build_block28.py','exec'))
exec(compile((R/'scripts/build_block29.py').read_text(),'build_block29.py','exec'))
exec(compile((R/'scripts/build_block30.py').read_text(),'build_block30.py','exec'))
exec(compile((R/'scripts/build_block31.py').read_text(),'build_block31.py','exec'))
exec(compile((R/'scripts/build_block32.py').read_text(),'build_block32.py','exec'))
exec(compile((R/'scripts/build_block33.py').read_text(),'build_block33.py','exec'))
exec(compile((R/'scripts/build_block34.py').read_text(),'build_block34.py','exec'))
exec(compile((R/'scripts/build_block35.py').read_text(),'build_block35.py','exec'))
exec(compile((R/'scripts/build_block36.py').read_text(),'build_block36.py','exec'))
exec(compile((R/'scripts/build_block37.py').read_text(),'build_block37.py','exec'))
exec(compile((R/'scripts/build_block38.py').read_text(),'build_block38.py','exec'))
exec(compile((R/'scripts/build_block39.py').read_text(),'build_block39.py','exec'))
exec(compile((R/'scripts/build_block40.py').read_text(),'build_block40.py','exec'))
exec(compile((R/'scripts/build_block41.py').read_text(),'build_block41.py','exec'))
exec(compile((R/'scripts/build_block42.py').read_text(),'build_block42.py','exec'))
exec(compile((R/'scripts/build_block43.py').read_text(),'build_block43.py','exec'))
exec(compile((R/'scripts/build_block44.py').read_text(),'build_block44.py','exec'))
exec(compile((R/'scripts/build_block45.py').read_text(),'build_block45.py','exec'))
exec(compile((R/'scripts/build_block46.py').read_text(),'build_block46.py','exec'))
exec(compile((R/'scripts/build_block47.py').read_text(),'build_block47.py','exec'))
exec(compile((R/'scripts/build_block48.py').read_text(),'build_block48.py','exec'))
exec(compile((R/'scripts/build_block49.py').read_text(),'build_block49.py','exec'))
exec(compile((R/'scripts/build_block50.py').read_text(),'build_block50.py','exec'))
exec(compile((R/'scripts/build_block51.py').read_text(),'build_block51.py','exec'))
exec(compile((R/'scripts/build_block52.py').read_text(),'build_block52.py','exec'))
exec(compile((R/'scripts/build_block53.py').read_text(),'build_block53.py','exec'))
exec(compile((R/'scripts/build_block54.py').read_text(),'build_block54.py','exec'))
exec(compile((R/'scripts/build_block55.py').read_text(),'build_block55.py','exec'))
exec(compile((R/'scripts/build_block56.py').read_text(),'build_block56.py','exec'))
exec(compile((R/'scripts/build_block57.py').read_text(),'build_block57.py','exec'))
exec(compile((R/'scripts/build_block58.py').read_text(),'build_block58.py','exec'))
exec(compile((R/'scripts/build_block59.py').read_text(),'build_block59.py','exec'))
exec(compile((R/'scripts/build_block60.py').read_text(),'build_block60.py','exec'))
exec(compile((R/'scripts/build_block61.py').read_text(),'build_block61.py','exec'))
exec(compile((R/'scripts/build_block62.py').read_text(),'build_block62.py','exec'))
exec(compile((R/'scripts/build_block63.py').read_text(),'build_block63.py','exec'))
exec(compile((R/'scripts/build_block64.py').read_text(),'build_block64.py','exec'))
exec(compile((R/'scripts/build_block65.py').read_text(),'build_block65.py','exec'))
exec(compile((R/'scripts/build_block66.py').read_text(),'build_block66.py','exec'))
exec(compile((R/'scripts/build_block67.py').read_text(),'build_block67.py','exec'))
exec(compile((R/'scripts/build_block68.py').read_text(),'build_block68.py','exec'))
exec(compile((R/'scripts/build_block69.py').read_text(),'build_block69.py','exec'))
exec(compile((R/'scripts/build_block70.py').read_text(),'build_block70.py','exec'))
exec(compile((R/'scripts/build_block71.py').read_text(),'build_block71.py','exec'))
exec(compile((R/'scripts/build_block72.py').read_text(),'build_block72.py','exec'))
exec(compile((R/'scripts/build_block73.py').read_text(),'build_block73.py','exec'))
exec(compile((R/'scripts/build_block74.py').read_text(),'build_block74.py','exec'))
exec(compile((R/'scripts/build_block75.py').read_text(),'build_block75.py','exec'))
exec(compile((R/'scripts/build_block76.py').read_text(),'build_block76.py','exec'))
exec(compile((R/'scripts/build_block77.py').read_text(),'build_block77.py','exec'))
exec(compile((R/'scripts/build_block78.py').read_text(),'build_block78.py','exec'))
exec(compile((R/'scripts/build_block79.py').read_text(),'build_block79.py','exec'))
exec(compile((R/'scripts/build_block80.py').read_text(),'build_block80.py','exec'))
exec(compile((R/'scripts/build_block81.py').read_text(),'build_block81.py','exec'))
exec(compile((R/'scripts/build_block82.py').read_text(),'build_block82.py','exec'))
exec(compile((R/'scripts/build_block83.py').read_text(),'build_block83.py','exec'))
exec(compile((R/'scripts/build_block84.py').read_text(),'build_block84.py','exec'))
exec(compile((R/'scripts/build_block85.py').read_text(),'build_block85.py','exec'))
exec(compile((R/'scripts/build_block86.py').read_text(),'build_block86.py','exec'))
exec(compile((R/'scripts/build_block87.py').read_text(),'build_block87.py','exec'))
exec(compile((R/'scripts/build_block88.py').read_text(),'build_block88.py','exec'))
exec(compile((R/'scripts/build_block89.py').read_text(),'build_block89.py','exec'))
# The rebuilt pass 26/28-88 meshes get the same export preparation as before (so the saved blend
# matches their repeatability hashes), but only the pass 60 mesh is written out.
extension_names=larm26_names+block28_names+block29_names+block30_names+block31_names+block32_names+block33_names+block34_names+block35_names+block36_names+block37_names+block38_names+block39_names+block40_names+block41_names+block42_names+block43_names+block44_names+block45_names+block46_names+block47_names+block48_names+block49_names+block50_names+block51_names+block52_names+block53_names+block54_names+block55_names+block56_names+block57_names+block58_names+block59_names+block60_names+block61_names+block62_names+block63_names+block64_names+block65_names+block66_names+block67_names+block68_names+block69_names+block70_names+block71_names+block72_names+block73_names+block74_names+block75_names+block76_names+block77_names+block78_names+block79_names+block80_names+block81_names+block82_names+block83_names+block84_names+block85_names+block86_names+block87_names+block88_names+block89_names;extension_cameras=block89_cameras
tail=(R/'scripts/rebuild_polish15.py').read_text();tail=tail[tail.index("exec(compile((R/'scripts/district_tangent_export.py')"):];tail=tail.replace('polish15-build.json','block89-build.json').replace('POLISH15_BUILD_OK','BLOCK89_BUILD_OK')
cut="audit[name]['export_frame_repairs']=export_district_fbx(obj,R/'exports/meshes'/(name+'.fbx'))"
assert cut in tail
tail=tail.replace(cut,"if name not in block89_names:continue\n "+cut)
exec(compile(tail,'export_block89','exec'))
report=json.loads((R/'previews/block89-build.json').read_text())
report['assets']={k:v for k,v in report['assets'].items() if k in block89_names};report['changed']=block89_names
report['prepared_unchanged']=larm26_names+block28_names+block29_names+block30_names+block31_names+block32_names+block33_names+block34_names+block35_names+block36_names+block37_names+block38_names+block39_names+block40_names+block41_names+block42_names+block43_names+block44_names+block45_names+block46_names+block47_names+block48_names+block49_names+block50_names+block51_names+block52_names+block53_names+block54_names+block55_names+block56_names+block57_names+block58_names+block59_names+block60_names+block61_names+block62_names+block63_names+block64_names+block65_names+block66_names+block67_names+block68_names+block69_names+block70_names+block71_names+block72_names+block73_names+block74_names+block75_names+block76_names+block77_names+block78_names+block79_names+block80_names+block81_names+block82_names+block83_names+block84_names+block85_names+block86_names+block87_names+block88_names
(R/'previews/block89-build.json').write_text(json.dumps(report,indent=2))
