"""Summarize measured pass-12 delivery evidence, without treating estimates as survey data."""
from pathlib import Path
import json,datetime
R=Path(__file__).resolve().parents[1];P=R/'previews'
read=lambda f:json.loads((P/f).read_text())
build=read('kvarnholmen-build.json');initial=read('kvarnholmen-import.json');refine=read('kvarnholmen-refine-import.json');scope=read('kvarnholmen-scope.json');collision=read('kvarnholmen-collision.json');render=read('kvarnholmen-render-audit.json');fbx=read('kvarnholmen-fbx-audit.json');walk=read('kvarnholmen-pie-walk.json');data=json.loads((R/'source/kvarnholmen.json').read_text())
checks={'blender_uv':build['status']=='passed','initial_import':initial['status']=='passed','refined_import':refine['status']=='passed','preservation':scope['status']=='passed','ground_and_walkable_clearance':collision['status']=='passed','render_frames':render['status']=='passed','exported_frames':all(v['vectors'] and not v['near_zero'] and not v['nonfinite'] for m in fbx.values() for v in m.values()),'pie_traversal':walk['status']=='passed'}
report={'status':'passed' if all(checks.values()) else 'review_required','time':datetime.datetime.now().isoformat(),'scope':'Mapped remaining district streets and building massing; facade detail deferred per user priority.','checks':checks,'named_streets':len(data['stats']['named_streets']),'new_building_masses':len(data['buildings']),'new_meshes':len(scope['new_assets']),'preserved_existing_assets':scope['existing_asset_specs_preserved'],'ground_samples':collision['floor_samples'],'missing_ground':len(collision['floor_failures']),'capsule_segments':collision['capsule_segments'],'centreline_furniture_contacts':len(collision['obstructions']),'verified_walking_detours':collision['verified_detours'],'unresolved_obstructions':collision['unresolved_obstructions'],'render_meshes_verified':len(render['meshes']),'pie_walk_m':walk['route_length_m'],'pie_samples':len(walk['samples']),'limitations':['Unknown heights, roofs and widths estimated; no individual photo-matching of new facades','Level terrain; quay and bridge structures simplified','No new performance benchmark or packaged-game test'],'preview':'previews/67_Kvarnholmen_Overview.png'}
(P/'kvarnholmen-delivery.json').write_text(json.dumps(report,indent=2,ensure_ascii=False));print(json.dumps({'status':report['status'],'checks':checks,'walk_m':report['pie_walk_m']},indent=2))
